#logging:
##  file:
##    path: E:\repositories\gadget-set\toolkit
##  file: toolkit.log
##  level:
##    root: info
##    art.lamzed.toolkit: info
#  config:
#    classpath: logback-toolkit.xml
logging:
  config:
    logback-toolkit.xml